#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config \
	mouse_follows_focus on \
	focus_follows_mouse on \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_topmost on \
	window_shadow on \
	window_animation_duration 0.3 \
	window_animation_frame_rate 120 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity off \
	insert_feedback_color 0xffd75f5f \
	active_window_border_color 0xff7793d1 \
	normal_window_border_color 0xff5e6798 \
	insert_feedback_color 0xff9dd274 \
	window_border_width 2 \
	window_border_radius 11 \
	window_border_blur off \
	window_border_hidpi off \
	window_border on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance on \
	top_padding 10 \
	bottom_padding 4 \
	left_padding 4 \
	right_padding 4 \
	window_gap 05 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

echo "yabai configuration loaded.."
# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:32:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:32:0
