#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items"     # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="FiraCode Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
NERD_FONT="FiraCode NF"
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
	blur_radius=30
	corner_radius=9
	height=40
	color=$BAR_COLOR
	# border_width=2
	# border_color=$BAR_BORDER_COLOR
	shadow=on
	position=top
	sticky=on
	padding_right=10
	padding_left=18
	y_offset=10
	margin=10
	topmost=off
	notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
	updates=when_shown
	icon.font="$FONT:Bold:14.0"
	icon.color=$ICON_COLOR
	icon.padding_left=$PADDINGS
	icon.padding_right=$PADDINGS
	label.font="$FONT:Semibold:13.0"
	label.color=$LABEL_COLOR
	label.padding_left=$PADDINGS
	label.padding_right=$PADDINGS
	padding_right=$PADDINGS
	padding_left=$PADDINGS
	background.height=26
	background.corner_radius=9
	background.border_width=2
	popup.background.border_width=2
	popup.background.corner_radius=9
	popup.background.border_color=$POPUP_BORDER_COLOR
	popup.background.color=$POPUP_BACKGROUND_COLOR
	popup.blur_radius=20
	popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

# Center
# source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/github.sh"
sketchybar -m --add item reminders right \
	--set reminders drawing=off \
	--set reminders update_freq=20 \
	--set reminders script="~/.config/sketchybar/plugins/reminders.sh" \
	--set reminders click_script="~/.config/sketchybar/plugins/reminders_click.sh"

source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/mic.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/clipboard.sh"
# source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/media.sh"

sketchybar --add alias TextInputMenuAgent right \
	--set TextInputMenuAgent alias.color="0xffffffff"
sketchybar --add alias LemonMonitor right \
	--set LemonMonitor alias.color="0xffffffff"

# S T A C K  I N D I C A T O R
sketchybar -m --add item stack_sep center \
	--add item stack center \
	--set stack script="$HOME/.config/sketchybar/plugins/stack.sh" \
	--subscribe stack window_focus front_app_switched space_change title_change \
	--set stack_sep drawing=off \
	--set stack drawing=off \
	--set stack update_freq=0

# M O D A L  I N D I C A T O R
sketchybar -m --add item modal left
sketchybar -m --set modal icon=[N]
sketchybar -m --set modal icon_color =0xFF83A1F1

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
